version: '3'
services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - nginx_conf:/etc/nginx/conf
      - ./requirements/nginx/ssl:/etc/nginx/ssl
    restart: always
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wp_data:/var/www/html
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception
    environment:
      WP_DB_HOST: mariadb
      WP_DB_USER: ${MYSQL_USER}
      WP_DB_PASSWORD: ${MYSQL_PASSWORD}
      WP_DB_NAME: ${MYSQL_DATABASE}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}

  mariadb:
    build: ./requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - inception
    env_file:
      - .env

volumes:
  wp_data:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/minabe/data/mysql
      o: bind
  nginx_conf:

networks:
  inception: