version: '3.1'
services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - ./requirements/nginx/html:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
    restart: always
    # networks:
    #   - inception-network
  wordpress:
    build: ./requirements/wordpress
    ports:
      - "9000"
    # depends_on:
    #   - mariadb
    volumes:
      - ./requirements/wordpress/src:/var/www/html
      - ./logs/wordpress/php:/var/log/php
    restart: always
    # networks:
    #   - inception-network

  # networks:
  #   inception-network:
  #     driver: bridge
