services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - ./vendor/src:/var/www/html
      - ./vendor/logs/nginx:/var/log/nginx
    restart: always
    environment:
      DOMAIN_NAME: $DOMAIN_NAME
    networks:
      - inception-net
  wordpress:
    build: ./requirements/wordpress
    ports:
      - "9000"
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./vendor/src:/var/www/html
      - ./vendor/logs/wordpress/php:/var/log/php
    restart: always
    environment:
      DB_NAME: $DB_NAME
      DB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      WP_URL: $WP_URL
      WP_TITLE: $WP_TITLE
      WP_ADMIN_USER: $WP_ADMIN_USER
      WP_ADMIN_PASSWORD: $WP_ADMIN_PASSWORD
      WP_ADMIN_EMAIL: $WP_ADMIN_EMAIL
      WP_EDITOR_USER: $WP_EDITOR_USER
      WP_EDITOR_PASSWORD: $WP_EDITOR_PASSWORD
      WP_EDITOR_EMAIL: $WP_EDITOR_EMAIL
    networks:
      - inception-net
  mariadb:
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    restart: always
    environment:
      DB_NAME: $DB_NAME
      DB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
    volumes:
      - ./vendor/data:/var/lib/mysql
      - ./vendor/logs/mariadb:/var/log/mysql
    networks:
      - inception-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: "30s" # 立ち上がるのに、30秒かかりそう
      retries: 30
      timeout: "5s"
      interval: "1s"

networks:
  inception-net:
