version: '3'
services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - nginx_conf:/etc/nginx/conf
      - ./requirements/nginx/ssl:/etc/nginx/ssl
    restart: always
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wp_data:/var/www/html
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env

  mariadb:
    build: ./requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - inception
    env_file:
      - .env

volumes:
  wp_data:
  db_data:
  nginx_conf:

networks:
  inception: