services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - ./vendor/src:/var/www/html
      - ./vendor/logs/nginx:/var/log/nginx
    restart: always
    networks:
      - inception-net
  wordpress:
    build: ./requirements/wordpress
    ports:
      - "9000"
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./vendor/src:/var/www/html
      - ./vendor/logs/wordpress/php:/var/log/php
    restart: always
    networks:
      - inception-net
  mariadb:
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./vendor/data:/var/lib/mysql
      - ./vendor/logs/mariadb:/var/log/mysql
    networks:
      - inception-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: "30s" # 立ち上がるのに、30秒かかりそう
      retries: 3
      timeout: "5s"       # 応答が5秒以上かかっても許さない
      interval: "60s"     # 60秒ごとにチェック

networks:
  inception-net:
