version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - nginx_conf:/etc/nginx/conf
      - ./nginx/ssl:/etc/nginx/ssl
    restart: on-failure
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    build: ./wordpress
    volumes:
      - wp_data:/var/www/html
    restart: on-failure
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env

  mariadb:
    build: ./mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: on-failure
    networks:
      - inception
    env_file:
      - .env

volumes:
  wp_data:
  db_data:
  nginx_conf:

networks:
  inception: