version: '3'

services:
  incep:
    build: ./all-in-one
    ports:
      - "80:80"

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - ./nginx:/etc/nginx/conf
  #     - web-root:/var/www/html
  #   depends_on:
  #     - wordpress
  #     - mariadb
  #   networks:
  #     - webnet

#   wordpress:
#     image: wordpress:php7.4-fpm-alpine
#     environment:
#       WORDPRESS_DB_HOST: mariadb
#       WORDPRESS_DB_USER: ${MYSQL_USER}
#       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
#       WORDPRESS_DB_NAME: wordpress
#     volumes:
#       - web-root:/var/www/html
#     networks:
#       - webnet

#   mariadb:
#     image: mariadb:latest
#     environment:
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MYSQL_DATABASE: wordpress
#       MYSQL_USER: ${MYSQL_USER}
#       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#     volumes:
#       - db-data:/var/lib/mysql
#     networks:
#       - webnet

# volumes:
#   db-data:
#   web-root:

# networks:
#   webnet:
